
services:
  _defaults:
    autowire: true
    autoconfigure: true

  #
  # --------------------------------------------------------------------------
  #   Request Transformers
  # --------------------------------------------------------------------------
  #

  # App\Presentation\Request\Transformer\:
  #   resource: '%kernel.project_dir%/app/Presentation/Request/Transformer'

  #
  # --------------------------------------------------------------------------
  #   Response Transformers
  # --------------------------------------------------------------------------
  #

  App\Presentation\Response\Transformer\:
    resource: '%kernel.project_dir%/app/Presentation/Response/Transformer'

  App\Presentation\Response\Transformer\ErrorResponseTransformer:
    arguments:
      $debug: '%kernel.debug%'

  App\Presentation\Response\Transformer\Search\SearchItemTransformer:
    arguments:
      $slugger: '@App\Infrastructure\Slug\CaseInsensitiveSlugger'
