
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Presentation\Controller\Api\Search\SearchItemResponseTransformer:
    arguments:
      $slugger: '@App\Infrastructure\Slug\CaseInsensitiveSlugger'
