parameters:
  env(DB_DATABASE): phplrt
  env(DB_HOST): postgres
  env(DB_PORT): 5432
  env(DB_USERNAME): user
  env(DB_PASSWORD): password

doctrine:
  dbal:
    default_connection: default
    #use_savepoints: true
    connections:
      default:
        dbname: '%env(string:DB_DATABASE)%'
        host: '%env(string:DB_HOST)%'
        port: '%env(int:DB_PORT)%'
        user: '%env(string:DB_USERNAME)%'
        password: '%env(string:DB_PASSWORD)%'
        server_version: '15.3'
        driver: pdo_pgsql
        logging: "%kernel.debug%"
        profiling: "%kernel.debug%"
        schema_filter: ~^(?!moonshine_)~
        mapping_types:
          pages_type: string
    types:
      App\Domain\Documentation\MenuId: App\Infrastructure\Persistence\Doctrine\Type\MenuIdType
      App\Domain\Documentation\PageId: App\Infrastructure\Persistence\Doctrine\Type\PageIdType
      App\Domain\Documentation\Search\IndexId: App\Infrastructure\Persistence\Doctrine\Type\IndexIdType

  orm:
    connection: ~
    default_entity_manager: ~
    auto_generate_proxy_classes: true
    proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
    proxy_namespace: Proxies
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    report_fields_where_declared: true
    enable_lazy_ghost_objects: true
    controller_resolver:
      auto_mapping: false
    mappings:
      App:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/app/Domain'
        prefix: 'App\Domain'
        alias: App

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
      metadata_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
