version: '3.4'

services:
  nginx:
    image: nginx:alpine
    container_name: phplrt-nginx
    working_dir: /home/phplrt/phplrt.org
    volumes:
      - .:/home/phplrt/phplrt.org
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/data/logs/nginx:/var/log/nginx/
    ports:
      - "${APP_HTTP_PUBLIC_PORT:-8081}:80"

  php:
    build: docker/php
    container_name: phplrt-php
    working_dir: /home/phplrt/phplrt.org
    volumes:
      - .:/home/phplrt/phplrt.org
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
