version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: phplrt-nginx
    working_dir: /home/phplrt/phplrt.org
    volumes:
      - .:/home/phplrt/phplrt.org
      - ./docker/nginx/phplrt.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/admin.phplrt.conf:/etc/nginx/conf.d/admin.conf
      - ./docker/data/logs/nginx:/var/log/nginx/
    ports:
      - "${APP_HTTP_PUBLIC_PORT:-8081}:80"
    networks:
      - phplrt_org

  php:
    build: docker/php
    container_name: phplrt-php
    working_dir: /home/phplrt/phplrt.org
    volumes:
      - .:/home/phplrt/phplrt.org
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - phplrt_org

  postgres:
    image: postgres:15.3
    container_name: phplrt-postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/data/postgres:/home/db
    environment:
      - POSTGRES_DB=${DB_DATABASE:-railt}
      - POSTGRES_USER=${DB_USERNAME:-user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
    ports:
      - "${APP_DATABASE_PUBLIC_PORT:-5432}:5432"
    networks:
      - phplrt_org

  node:
    build: docker/node
    container_name: phplrt-node
    working_dir: /home/phplrt/phplrt.org
    volumes:
      - .:/home/phplrt/phplrt.org

networks:
  phplrt_org:
    name: phplrt_org
    driver: bridge

volumes:
  postgres:
