
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Domain\:
    resource: '%kernel.project_dir%/app/Domain'

  #
  # -----------------------------------------------------------------------------
  #   Database Repositories
  # -----------------------------------------------------------------------------
  #

  App\Domain\Documentation\Search\IndexRepositoryInterface:
    class: App\Infrastructure\Persistence\Repository\IndexDatabaseRepository

  App\Domain\Documentation\MenuRepositoryInterface:
    class: App\Infrastructure\Persistence\Repository\MenuDatabaseRepository

  App\Domain\Documentation\PageRepositoryInterface:
    class: App\Infrastructure\Persistence\Repository\PageDatabaseRepository
