
services:
  _defaults:
    autowire: true
    autoconfigure: true

  #
  # --------------------------------------------------------------------------
  #   Request Listeners
  # --------------------------------------------------------------------------
  #

  # ...

  #
  # --------------------------------------------------------------------------
  #   Response Listeners
  # --------------------------------------------------------------------------
  #

  App\Infrastructure\Listener\ExceptionLoggerListener:
    tags: [ { name: kernel.event_listener, priority: 1023 } ]

  App\Infrastructure\Listener\FailedResponseListener:
    tags: [ { name: kernel.event_listener, priority: 1024 } ]

  App\Infrastructure\Listener\SuccessfulResponseListener:
    arguments:
      $default: '@Local\HttpFactory\Driver\JsonDriver'
    tags: [ { name: kernel.event_listener, priority: 1 } ]

  App\Infrastructure\Listener\Exception\StatusCodeConverter:
    arguments:
      $mappings:
        Symfony\Component\Validator\Exception\ValidationFailedException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_UNPROCESSABLE_ENTITY
      $default: !php/const Symfony\Component\HttpFoundation\Response::HTTP_INTERNAL_SERVER_ERROR
