
services:
  _defaults:
    autowire: true
    autoconfigure: true

  # ----------------------------------------------------------------------------
  #   Exception Converters
  # ----------------------------------------------------------------------------

  App\Presentation\Response\Listener\Exception\StatusCodeConverter:
    arguments:
      $mappings:
        Symfony\Component\Validator\Exception\ValidationFailedException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_UNPROCESSABLE_ENTITY
      $default: !php/const Symfony\Component\HttpFoundation\Response::HTTP_INTERNAL_SERVER_ERROR
